### ISSUE TITLE
Map vs List of tuples?

### ISSUE THREAD

**Issue by pkese** [fjoppe/Legivel#11]
Hi Frank,

I have a Yaml object in which I need to preserve ordering of items (e.g. when iterating over object "world cup" should come before "superbowl"):
```yaml
recent_searches:
    world cup: 71
    superbowl: 5
    hurricane florence: 3
    donald trump: 81
```
Now if I model this as `{recent_searches: Map<string,int>}` then I loose that ordering.

Is it possible to somehow model this in a way to get a list of tuples as a result:  
`{recent_searches: List<string,int>}`.

Yes, I know, minuses in yaml document would help, but unfortunately in this case I can't change the yaml source - it's probably done so, because it's using yaml's `&` and `*` references all over the place to build these objects.

I'm just fishing for ideas. Any hint will help if you happen to have one.

Thanks
