### ISSUE TITLE
Deserialize Discriminated Union with primitive scalar data type

### ISSUE THREAD

**Issue by Brains** [fjoppe/Legivel#13]
### Description

Need to deserialize `Discriminated Union` with primitive `int` data. 
Don't want to use attributes `YamlValue, YamlField` to keep types clear for easy usage from `F# Interactive`

### Repro steps
1. Define types
```fs
type Salary =
    | Hourly  of int
    | Monthly of int

type User = {
    name: string
    dept: string
    cost: Salary }
```
2. Try to deserialize it from different `.yml` files:
```fs
System.IO.File.ReadAllText "Datas\Users.yml" 
|> Serialization.Deserialize<User>
```

```yml
name: Albert Einstein
dept: Physics
cost: Hourly 65
---
name: Albert Einstein
dept: Physics
cost: Hourly (65)
---
name: Albert Einstein
dept: Physics
cost: {Hourly,65}
---
```

### Expected behavior

Deserialize all data successfully

### Actual behavior

Errors:
```hs
Message = "Union case 'Hourly 65' not availble in type: 'FSI_0075+Salary'"
Message = "Missing value for field: 'cost'"
Message = "Expecting a Scalar Node"
Message = "Document cannot be mapped"
Message = "Type mismatch 'tag:yaml.org,2002:map' for tag: Int32"
```

### Known workarounds

Even with attributes `YamlValue, YamlField` can't manage it to work:

```fs
[<YamlField("TypeOf")>]
type Salary =
    | Hourly
    | Monthly of int

System.IO.File.ReadAllText "Datas\Users.yml" 
|> Serialization.Deserialize<Salary>
```
```yml
null: 60
TypeOf: Monthly
---
TypeOf: {Monthly,60}
```
