### ISSUE TITLE
Typecast question

### ISSUE THREAD

**Issue by pkese** [fjoppe/Legivel#16]
Frank,

I'm having a schema defined like this:
```fsharp
type Doc = {
    t1: string list
    t2: Map<string, int>
    t3: Map<int, string>
}
```

And a document:
```yaml
t1: [yes, maybe, no]
t2: {true: 2, false: 0, ambiguous: 1, null: -1}
t3: {1: yes, 0: maybe, -1: no}
```

Legivel says the document is incorrect: it can't cast `yes` into a string unless it is quoted even though the schema says to specifically interpret it as string. Technically it is a valid yaml document.

Is this worth pursuing / duscussing, or should I better ask my Php and Python peers, if they can fix the document by adding additional quotes?

Thanks
