### ISSUE TITLE
Provide an option to report mistyped keys

### ISSUE THREAD

**Issue by pkese** [fjoppe/Legivel#8]
Having defined a type
```fsharp
type Contact = {
  name: string
  phone: string option // phone is optional
}
```
And a yaml document
```yaml
---
name: Paul
ophne: 111-222-333 # note mistyped key `ophne` instead of `phone`
```

...deserializaton with `Deserialize<Contact>(yaml)` doesn't fail or warn on mismatching keys so a mistyped entry would pass unnoticed possibly causing semantic errors.

It would be beneficial if there was an alternative *strict* version of Deserialize that would fail (or warn) on any keys that don't adhere to the schema.

P.S. Is there a way to somehow get this functionality in the advanced (Parser + Mapper) mode? I didn't notice it in the documentation.

P.P.S. It's a great library btw... Sorry for complaining so much ;-)
